config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/login', to: "sessions#new"

  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"

  get '/help', to: "static_pages#help"

  get '/about', to: "static_pages#about"

  get '/contact', to: "static_pages#contact"

  root "static_pages#home"

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new,:edit,:create,:update]

  resources :microposts, only: [:create,:destroy]

  resources :relationships, only: [:create,:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_not_logged_in.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href = "http://www.railstutorial.org/">Ruby on Rails Rutorial</a>
    sample application
  </h2>
  <%= link_to "Sign up now!",signup_path,class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png",alt: "Rails logo"),
            'http://rubyrails.org/' %>

app/views/static_pages/about.html.erb
<%provide(:title,"about")%>
<h1>about</h1>

app/views/static_pages/contact.html.erb
<%provide(:title,"contact")%>
<h1>contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<%provide(:title,"help")%>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%provide(:title,"home")%>
<% if logged_in? %>
  <%= render 'static_pages/logged_in' %>
<% else %>
  <%= render 'static_pages/not_logged_in'%>
<% end %>