config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/login', to: "sessions#new"

  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"

  get '/help', to: "static_pages#help"

  get '/about', to: "static_pages#about"

  get '/contact', to: "static_pages#contact"

  root "static_pages#home"

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new,:edit,:create,:update]

  resources :microposts, only: [:create,:destroy]

  resources :relationships, only: [:create,:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture,PictureUploader
  validates :user_id,presence: true
  validates :content,presence: true, length: {maximum: 140}
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture,"should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user,only:[:create,:destroy]
  before_action :correct_user,only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items=[]
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def correct_user
      @micropost = current_user.microposts.find_by(id:params[:id])
      redirect_to root_url if @micropost.nil?
    end
    def micropost_params
      params.require(:micropost).permit(:content,:picture)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%=micropost.id%>">
  <%= link_to gravatar_for(micropost.user,size:50),user_path(micropost.user) %>
  <span class="user"><%= link_to micropost.user.name, user_path(micropost.user)%></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete",micropost_path(micropost),method: :delete,data:{confirm: "You sure?"} %>
    <% end %>
  </span>
</li>